spring.datasource.url=jdbc:postgresql://dpg-cub1j2id3nsc73b9rcb0-a.oregon-postgres.render.com:5432/base_datos_crud
spring.datasource.username=base_datos_crud_user
spring.datasource.password=wGrCKWLPlz2mpH9qLSBinzL91qL4FrR
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jakarta.persistence.jdbc.url=jdbc:postgresql://dpg-cub1j2id3nsc73b9rcb0-a.oregon-postgres.render.com:5432/base_datos_crud
jakarta.persistence.jdbc.user=base_datos_crud_user
jakarta.persistence.jdbc.password=wGrCKWLPlz2mpH9qLSBinzL91qL4FrR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true